---
- name: install curl
  apt: pkg=curl
       state=present
       update_cache=yes


- name: install docker compose
  get_url: url=https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
           dest=/usr/local/bin/docker-compose
           owner=root
           group=root
           mode=755


- name: install docker compose bash completion
  get_url: url=https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/bash/docker-compose
           dest=/etc/bash_completion.d/docker-compose
           owner=root
           group=root
           mode=755
